/**
 * N02の事業者表示名を、公式案内で確認したICブランドへ結び付けるカタログ。
 * N02は名称と地図形状の照合にだけ使い、IC利用可否の根拠にはしない。
 */
export const SHINKANSEN_OPERATOR_TYPE = '1';

export const OPERATOR_TO_AREA = {
  // JR
  北海道旅客鉄道: 'kitaca',
  東日本旅客鉄道: 'suica',
  東海旅客鉄道: 'toica',
  西日本旅客鉄道: 'icoca',
  四国旅客鉄道: 'icoca',
  九州旅客鉄道: 'sugoca',

  // Suica・地域連携Suica
  東京モノレール: 'suica',
  東京臨海高速鉄道: 'suica',
  埼玉新都市交通: 'suica',
  仙台空港鉄道: 'suica',
  伊豆急行: 'suica',
  富士山麓電気鉄道: 'suica',
  富士急行: 'suica',
  しなの鉄道: 'suica',
  上毛電気鉄道: 'suica',
  宇都宮ライトレール: 'suica',
  沖縄都市モノレール: 'suica',
  青い森鉄道: 'suica',
  アイジーアールいわて銀河鉄道: 'suica',
  三陸鉄道: 'suica',
  阿武隈急行: 'suica',
  福島交通: 'suica',
  会津鉄道: 'suica',
  山形鉄道: 'suica',
  秋田内陸縦貫鉄道: 'suica',
  由利高原鉄道: 'suica',
  弘南鉄道: 'suica',
  津軽鉄道: 'suica',
  えちごトキめき鉄道: 'suica',
  北越急行: 'suica',
  長野電鉄: 'suica',
  アルピコ交通: 'suica',
  上田電鉄: 'suica',
  上信電鉄: 'suica',
  わたらせ渓谷鐵道: 'suica',
  真岡鐵道: 'suica',
  ひたちなか海浜鉄道: 'suica',
  鹿島臨海鉄道: 'suica',
  いすみ鉄道: 'suica',
  小湊鐵道: 'suica',

  // PASMO
  東京地下鉄: 'pasmo',
  東京都: 'pasmo',
  東急電鉄: 'pasmo',
  東武鉄道: 'pasmo',
  西武鉄道: 'pasmo',
  小田急電鉄: 'pasmo',
  京王電鉄: 'pasmo',
  京成電鉄: 'pasmo',
  京浜急行電鉄: 'pasmo',
  相模鉄道: 'pasmo',
  横浜市: 'pasmo',
  横浜高速鉄道: 'pasmo',
  首都圏新都市鉄道: 'pasmo',
  埼玉高速鉄道: 'pasmo',
  東葉高速鉄道: 'pasmo',
  北総鉄道: 'pasmo',
  千葉都市モノレール: 'pasmo',
  多摩都市モノレール: 'pasmo',
  ゆりかもめ: 'pasmo',
  湘南モノレール: 'pasmo',
  江ノ島電鉄: 'pasmo',
  京葉臨海鉄道: 'pasmo',
  新京成電鉄: 'pasmo',
  舞浜リゾートライン: 'pasmo',
  伊豆箱根鉄道: 'pasmo',
  箱根登山鉄道: 'pasmo',
  小田急箱根: 'pasmo',
  秩父鉄道: 'pasmo',
  流鉄: 'pasmo',
  銚子電気鉄道: 'pasmo',
  横浜シーサイドライン: 'pasmo',
  山万: 'pasmo',
  芝山鉄道: 'pasmo',
  関東鉄道: 'kanto-railway',

  // manaca・TOICA
  名古屋鉄道: 'manaca',
  名古屋市: 'manaca',
  名古屋臨海高速鉄道: 'manaca',
  豊橋鉄道: 'manaca',
  愛知高速交通: 'manaca',
  名古屋ガイドウェイバス: 'manaca',
  愛知環状鉄道: 'toica',
  遠州鉄道: 'toica',
  天竜浜名湖鉄道: 'toica',
  大井川鐵道: 'toica',
  岳南電車: 'toica',
  JR東海交通事業: 'toica',

  // PiTaPa
  阪急電鉄: 'pitapa',
  阪神電気鉄道: 'pitapa',
  京阪電気鉄道: 'pitapa',
  南海電気鉄道: 'pitapa',
  近畿日本鉄道: 'pitapa',
  大阪市高速電気軌道: 'pitapa',
  大阪モノレール: 'pitapa',
  北大阪急行電鉄: 'pitapa',
  神戸市: 'pitapa',
  京都市: 'pitapa',
  神戸新交通: 'pitapa',
  神戸電鉄: 'pitapa',
  山陽電気鉄道: 'pitapa',
  能勢電鉄: 'pitapa',
  叡山電鉄: 'pitapa',
  京福電気鉄道: 'pitapa',
  阪堺電気軌道: 'pitapa',
  水間鉄道: 'pitapa',
  養老鉄道: 'pitapa',
  伊勢鉄道: 'pitapa',
  岡山電気軌道: 'pitapa',
  静岡鉄道: 'pitapa',

  // ICOCA
  広島電鉄: 'icoca',
  広島高速交通: 'icoca',
  あいの風とやま鉄道: 'icoca',
  'IRいしかわ鉄道': 'icoca',
  ハピラインふくい: 'icoca',
  富山地方鉄道: 'icoca',
  万葉線: 'icoca',
  福井鉄道: 'icoca',
  えちぜん鉄道: 'icoca',
  伊予鉄道: 'icoca',
  近江鉄道: 'icoca',
  三岐鉄道: 'icoca',
  伊賀鉄道: 'icoca',
  四日市あすなろう鉄道: 'icoca',
  北条鉄道: 'icoca',
  一畑電車: 'icoca',
  井原鉄道: 'icoca',
  水島臨海鉄道: 'icoca',
  北陸鉄道: 'icoca',
  'WILLER　TRAINS': 'icoca',
  和歌山電鐵: 'icoca',
  のと鉄道: 'icoca',

  // 地域カード・九州
  高松琴平電気鉄道: 'iruca',
  西日本鉄道: 'nimoca',
  筑豊電気鉄道: 'nimoca',
  熊本市: 'nimoca',
  函館市: 'nimoca',
  長崎電気軌道: 'nimoca',
  松浦鉄道: 'nimoca',
  平成筑豊鉄道: 'nimoca',
  熊本電気鉄道: 'nimoca',
  甘木鉄道: 'nimoca',
  福岡市: 'hayakaken',
  札幌市: 'sapica',
  一般社団法人札幌市交通事業振興公社: 'sapica',
  仙台市: 'icsca',
  北九州高速鉄道: 'sugoca',
  肥薩おれんじ鉄道: 'sugoca',
  道南いさりび鉄道: 'kitaca',

  // N02には残すが、IC可否を割り当てない事業者
  長良川鉄道: 'other',
  樽見鉄道: 'other',
  明知鉄道: 'other',
  智頭急行: 'other',
  若桜鉄道: 'other',
  くま川鉄道: 'other',
  南阿蘇鉄道: 'other',
  島原鉄道: 'other',
  鹿児島市: 'other',
};

export function brandForOperator(operator) {
  return OPERATOR_TO_AREA[operator] ?? null;
}
